package com.komod.api.domain.model

data class WardrobeItemDetail(
    val id: String,
    val imageId: String,
    val imageUrl: String?,
    val status: Int,
    val category: String,
    val subcategory: String?,
    val itemName: String?,
    val brand: String?,
    val bodyRegion: String?,
    val layer: String?,
    val primaryColor: String?,
    val secondaryColors: List<String>?,
    val accentColors: List<String>?,
    val pattern: String?,
    val material: String?,
    val texture: String?,
    val fit: String?,
    val silhouette: String?,
    val sleeveLength: String?,
    val pantLength: String?,
    val neckline: String?,
    val collarType: String?,
    val closure: String?,
    val formality: String?,
    val style: List<String>?,
    val season: List<String>?,
    val occasion: List<String>?,
    val genderStyle: String?,
    val weatherMinTempC: Int?,
    val weatherMaxTempC: Int?,
    val weatherRainFriendly: Boolean?,
    val warmthLevel: String?,
    val features: List<String>?,
    val recommendedPairings: List<String>?,
    val embeddingDescription: String?,
    val isFavorite: Boolean,
    val confidence: Double,
    val createdAt: String,
    val boundingBox: BoundingBox,
    // Raw (unsigned) storage paths, kept alongside the already-signed [imageUrl] so the
    // upcoming Crop Editor flow can request the original photo and know whether a crop
    // already exists, without re-deriving these from the DTO layer.
    val originalImageStoragePath: String? = null,
    val croppedImageStoragePath: String? = null,
)
