package com.komod.api.presentation.outfits

import com.komod.api.domain.model.Outfit
import com.komod.api.domain.model.OutfitOccasion
import com.komod.api.domain.model.OutfitStyle

data class OutfitUiState(
    val selectedOccasion: OutfitOccasion = OutfitOccasion.Outdoor,
    val selectedStyle: OutfitStyle? = null,
    val outfits: List<Outfit> = emptyList(),
    val isGenerating: Boolean = false,
    val errorMessage: String? = null,
    // Retrying won't fix a daily generation limit, so the screen hides the Retry button
    // when this is set — see OutfitViewModel.generateOutfits().
    val isPlanLimitError: Boolean = false,
    val hasAutoGenerated: Boolean = false,
    val weatherUiState: WeatherUiState = WeatherUiState.WeatherDisabled,
    val savingOutfitIds: Set<String> = emptySet(),
    val unsavingOutfitIds: Set<String> = emptySet(),
    // outfit.id -> server-assigned saved outfit id, used to target DELETE /v1/outfits/{id}
    val savedOutfitIds: Map<String, String> = emptyMap(),
)
